# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import goods.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(upload_to=goods.models.Item.UPLOAD_TO, verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('link', models.CharField(max_length=2500, verbose_name='link')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Edited')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-published'],
            },
        ),
    ]
